# Generated by Django 3.2 on 2022-06-12 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iReview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='content',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='design',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='usability',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('rate', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
